// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ZZvPzszvcfTlgc2QxCOX4IGwnB7Wo9w',
    appId: '1:507366207919:web:bb73f0cc3780b79484ff5a',
    messagingSenderId: '507366207919',
    projectId: 'chatcito-9515e',
    authDomain: 'chatcito-9515e.firebaseapp.com',
    databaseURL: 'https://chatcito-9515e-default-rtdb.firebaseio.com',
    storageBucket: 'chatcito-9515e.firebasestorage.app',
    measurementId: 'G-68VWDTK8B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSu9ej5ntrs871ymJG_2PLA5nh_s3ZmCI',
    appId: '1:507366207919:android:1f6a41a756c58c3c84ff5a',
    messagingSenderId: '507366207919',
    projectId: 'chatcito-9515e',
    databaseURL: 'https://chatcito-9515e-default-rtdb.firebaseio.com',
    storageBucket: 'chatcito-9515e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChlcP4krxO_YjOXoYrh-dJIBdAwSLLHQA',
    appId: '1:507366207919:ios:52aeba57a4f687ad84ff5a',
    messagingSenderId: '507366207919',
    projectId: 'chatcito-9515e',
    databaseURL: 'https://chatcito-9515e-default-rtdb.firebaseio.com',
    storageBucket: 'chatcito-9515e.firebasestorage.app',
    iosBundleId: 'com.example.pryFirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChlcP4krxO_YjOXoYrh-dJIBdAwSLLHQA',
    appId: '1:507366207919:ios:52aeba57a4f687ad84ff5a',
    messagingSenderId: '507366207919',
    projectId: 'chatcito-9515e',
    databaseURL: 'https://chatcito-9515e-default-rtdb.firebaseio.com',
    storageBucket: 'chatcito-9515e.firebasestorage.app',
    iosBundleId: 'com.example.pryFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0ZZvPzszvcfTlgc2QxCOX4IGwnB7Wo9w',
    appId: '1:507366207919:web:c9cf06c40c0e85ea84ff5a',
    messagingSenderId: '507366207919',
    projectId: 'chatcito-9515e',
    authDomain: 'chatcito-9515e.firebaseapp.com',
    databaseURL: 'https://chatcito-9515e-default-rtdb.firebaseio.com',
    storageBucket: 'chatcito-9515e.firebasestorage.app',
    measurementId: 'G-X9FQKEXVLM',
  );
}
